
// User
const USER_ACCOUNT_KEY = "USER_ACCOUNT_KEY";
const SET_ACCOUNT_USER = "SET_ACCOUNT_USER";
const GET_LIST_USER = "GET_LIST_USER";
const GET_INFO_USER = "GET_INFO_USER";



export {
    USER_ACCOUNT_KEY,
    SET_ACCOUNT_USER,
    GET_INFO_USER,
    GET_LIST_USER,
}